services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s


  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: 
      KC_BOOTSTRAP_ADMIN_PASSWORD: 
      KC_DB: 
      KC_DB_URL: 
      KC_DB_USERNAME: 
      KC_DB_PASSWORD: 
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
